/* Generated by Yosys 0.6 (git sha1 UNKNOWN, clang 3.4-1ubuntu3 -fPIC -Os) */

module FA(a, b, ci, co, s);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input a;
  input b;
  input ci;
  output co;
  output s;
  AND2X2 _07_ (
    .A(a),
    .B(ci),
    .Y(_03_)
  );
  NOR2X1 _08_ (
    .A(a),
    .B(ci),
    .Y(_04_)
  );
  OAI21X1 _09_ (
    .A(_03_),
    .B(_04_),
    .C(b),
    .Y(_05_)
  );
  INVX1 _10_ (
    .A(b),
    .Y(_06_)
  );
  NAND2X1 _11_ (
    .A(a),
    .B(ci),
    .Y(_00_)
  );
  OR2X2 _12_ (
    .A(a),
    .B(ci),
    .Y(_01_)
  );
  NAND3X1 _13_ (
    .A(_06_),
    .B(_00_),
    .C(_01_),
    .Y(_02_)
  );
  NAND2X1 _14_ (
    .A(_05_),
    .B(_02_),
    .Y(s)
  );
  AOI21X1 _15_ (
    .A(_06_),
    .B(_00_),
    .C(_04_),
    .Y(co)
  );
endmodule

module RCA(A, B, Ci, Co, S);
  input [3:0] A;
  input [3:0] B;
  input Ci;
  output Co;
  output [3:0] S;
  wire [4:0] c;
  FA \addbit[0].bit  (
    .a(A[0]),
    .b(B[0]),
    .ci(Ci),
    .co(c[1]),
    .s(S[0])
  );
  FA \addbit[1].bit  (
    .a(A[1]),
    .b(B[1]),
    .ci(c[1]),
    .co(c[2]),
    .s(S[1])
  );
  FA \addbit[2].bit  (
    .a(A[2]),
    .b(B[2]),
    .ci(c[2]),
    .co(c[3]),
    .s(S[2])
  );
  FA \addbit[3].bit  (
    .a(A[3]),
    .b(B[3]),
    .ci(c[3]),
    .co(Co),
    .s(S[3])
  );
endmodule
